version: "3.4"
services:
    # PHP Service
    app:
        image: sound-box
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./php.ini:/usr/local/etc/php/php.ini
        environment:
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
        links:
            - db
    db:
        platform: linux/amd64 # for platform error on Apple M1 chips
        restart: always
        env_file: .env
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            TZ: Asia/Ho_Chi_Minh
        volumes:
            - database:/var/lib/mysql
        ports:
            - "3306:3306"

    # Nginx Service
    webserver:
        image: nginx:1.17-alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    database:
